services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    enviroment:
      SA_PASSWORD: "PruebaDepoQuick"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data